import { Word } from '../types';

export const CULTURE_VOCABULARY: Word[] = [
    { term: "A melting-pot", partOfSpeech: "n", definition: "A mix of cultures and races.", translation: "Sự pha trộn văn hóa", category: "Culture" },
    { term: "Acculturation", partOfSpeech: "n", definition: "Adapting to another culture.", translation: "Giao lưu văn hóa", category: "Culture" },
    { term: "Biculturalism", partOfSpeech: "n", definition: "Belonging to two different cultures.", translation: "Song văn hóa", category: "Culture" },
    { term: "Bro culture", partOfSpeech: "n", definition: "Culture of young males who like partying and sports.", translation: "Văn hóa anh em", category: "Culture" },
    { term: "Chauvinism", partOfSpeech: "n", definition: "Excessive prejudice for one's own group.", translation: "Chủ nghĩa sô vanh", category: "Culture" },
    { term: "Civilization", partOfSpeech: "n", definition: "An advanced human society.", translation: "Nền văn minh", category: "Culture" },
    { term: "Commercialism", partOfSpeech: "n", definition: "Focus on commercial profit.", translation: "Chủ nghĩa trọng thương", category: "Culture" },
    { term: "Contemporary culture", partOfSpeech: "n", definition: "Modern culture.", translation: "Văn hóa đương đại", category: "Culture" },
    { term: "Counter-culture", partOfSpeech: "n", definition: "Culture opposing mainstream values.", translation: "Phản văn hóa", category: "Culture" },
    { term: "Culture diffusion", partOfSpeech: "n", definition: "The spread of cultural elements.", translation: "Sự lan truyền văn hóa", category: "Culture" },
    { term: "Cultural conflict", partOfSpeech: "n", definition: "Clash between cultures.", translation: "Xung đột văn hóa", category: "Culture" },
    { term: "Cultural relativism", partOfSpeech: "n", definition: "View that cultural values are context-dependent.", translation: "Thuyết tương đối văn hóa", category: "Culture" },
    { term: "Culture shock", partOfSpeech: "n", definition: "Disorientation from new culture.", translation: "Cú sốc văn hóa", category: "Culture" },
    { term: "Cyberculture", partOfSpeech: "n", definition: "Culture of the internet.", translation: "Văn hóa mạng", category: "Culture" },
    { term: "Denominationalism", partOfSpeech: "n", definition: "Emphasis on religious differences.", translation: "Thái độ bè phái", category: "Culture" },
    { term: "Discrimination", partOfSpeech: "n", definition: "Unfair treatment based on differences.", translation: "Sự phân biệt đối xử", category: "Culture" },
    { term: "Enculturation", partOfSpeech: "n", definition: "Learning one's own culture.", translation: "Hội nhập văn hóa", category: "Culture" },
    { term: "Epistemology", partOfSpeech: "n", definition: "Theory of knowledge.", translation: "Nhận thức luận", category: "Culture" },
    { term: "Exotic culture", partOfSpeech: "n", definition: "Foreign or unusual culture.", translation: "Văn hóa ngoại lai", category: "Culture" },
    { term: "Folk culture", partOfSpeech: "n", definition: "Traditional culture of common people.", translation: "Văn hóa dân gian", category: "Culture" },
    { term: "Homogeneous", partOfSpeech: "adj", definition: "Of the same kind throughout.", translation: "Đồng nhất", category: "Culture" },
    { term: "Heritage", partOfSpeech: "n", definition: "Inherited traditions and culture.", translation: "Di sản", category: "Culture" },
    { term: "Indigenous culture", partOfSpeech: "n", definition: "Native or original culture.", translation: "Văn hóa bản địa", category: "Culture" },
    { term: "Intellectualism", partOfSpeech: "n", definition: "Emphasis on intellectual pursuits.", translation: "Thuyết duy lý trí", category: "Culture" },
    { term: "Latitudinarian", partOfSpeech: "adj", definition: "Liberal and open-minded.", translation: "Phóng khoáng", category: "Culture" },
    { term: "Multiculturalism", partOfSpeech: "n", definition: "Coexistence of diverse cultures.", translation: "Đa văn hóa", category: "Culture" },
    { term: "Nostalgic", partOfSpeech: "adj", definition: "Longing for the past.", translation: "Hoài cổ", category: "Culture" },
    { term: "Ontogeny", partOfSpeech: "n", definition: "Development of an organism.", translation: "Phát triển cá thể", category: "Culture" },
    { term: "Patriotism", partOfSpeech: "n", definition: "Love for one's country.", translation: "Lòng yêu nước", category: "Culture" },
    { term: "Peoplehood", partOfSpeech: "n", definition: "The quality of being a distinct people.", translation: "Đặc tính dân tộc", category: "Culture" },
    { term: "Pop culture", partOfSpeech: "n", definition: "Popular culture of ordinary people.", translation: "Văn hóa đại chúng", category: "Culture" },
    { term: "Sacred cow", partOfSpeech: "n", definition: "Something exempt from criticism.", translation: "Điều bất khả xâm phạm", category: "Culture" },
    { term: "Social stratification", partOfSpeech: "n", definition: "Division of society into layers.", translation: "Phân tầng xã hội", category: "Culture" },
    { term: "Stereotype", partOfSpeech: "n", definition: "Fixed belief about a group.", translation: "Khuôn mẫu", category: "Culture" },
    { term: "Subculture", partOfSpeech: "n", definition: "A distinct culture within a larger one.", translation: "Tiểu văn hóa", category: "Culture" },
    { term: "Supremacism", partOfSpeech: "n", definition: "Belief in superiority of a group.", translation: "Thuyết ưu thế", category: "Culture" },
    { term: "Transculturation", partOfSpeech: "n", definition: "Cultural transformation.", translation: "Di chuyển văn hóa", category: "Culture" },
    { term: "Cultural heritage", partOfSpeech: "n", definition: "Inherited cultural traditions.", translation: "Di sản văn hóa", category: "Culture" },
    { term: "Cultural identity", partOfSpeech: "n", definition: "Sense of belonging to a culture.", translation: "Bản sắc văn hóa", category: "Culture" },
    { term: "Cultural integration", partOfSpeech: "n", definition: "Blending of cultures.", translation: "Hội nhập văn hóa", category: "Culture" },
    { term: "Core values", partOfSpeech: "n", definition: "Fundamental beliefs.", translation: "Giá trị cốt lõi", category: "Culture" },
];
