import { Word } from '../types';

export const ECONOMY_VOCABULARY: Word[] = [
    { term: "Accelerated depreciation", partOfSpeech: "n", definition: "Faster depreciation in early years.", translation: "Khấu hao nhanh", category: "Economy" },
    { term: "Accommodating monetary policy", partOfSpeech: "n", definition: "Policy allowing money supply to grow.", translation: "Chính sách tiền tệ thích ứng", category: "Economy" },
    { term: "Active balance", partOfSpeech: "n", definition: "Money regularly circulating.", translation: "Số dư hoạt động", category: "Economy" },
    { term: "Aggregate output", partOfSpeech: "n", definition: "Total value of goods/services produced (GDP).", translation: "Tổng sản lượng", category: "Economy" },
    { term: "Amortize", partOfSpeech: "v", definition: "To pay off debt gradually.", translation: "Trả dần", category: "Economy" },
    { term: "Autarky", partOfSpeech: "n", definition: "Economic self-sufficiency.", translation: "Tự cung tự cấp", category: "Economy" },
    { term: "Balanced growth", partOfSpeech: "n", definition: "Proportional economic growth.", translation: "Tăng trưởng cân đối", category: "Economy" },
    { term: "Bilateral assistance", partOfSpeech: "n", definition: "Aid between two countries.", translation: "Trợ giúp song phương", category: "Economy" },
    { term: "Budget deficit", partOfSpeech: "n", definition: "When spending exceeds income.", translation: "Thâm hụt ngân sách", category: "Economy" },
    { term: "Buffer stocks", partOfSpeech: "n", definition: "Reserve goods to stabilize prices.", translation: "Dự trữ điều hòa", category: "Economy" },
    { term: "Capital expenditure", partOfSpeech: "n", definition: "Investment in fixed assets.", translation: "Chi phí vốn", category: "Economy" },
    { term: "Credit crunch", partOfSpeech: "n", definition: "Sudden shortage of available loans.", translation: "Thắt chặt tín dụng", category: "Economy" },
    { term: "Deflation", partOfSpeech: "n", definition: "Decrease in general price levels.", translation: "Giảm phát", category: "Economy" },
    { term: "Earning per share", partOfSpeech: "n", definition: "Company profit divided by shares.", translation: "Thu nhập trên cổ phiếu", category: "Economy" },
    { term: "E-commerce", partOfSpeech: "n", definition: "Commercial transactions online.", translation: "Thương mại điện tử", category: "Economy" },
    { term: "Economic recession", partOfSpeech: "n", definition: "Period of economic decline.", translation: "Suy thoái kinh tế", category: "Economy" },
    { term: "Embargo", partOfSpeech: "n", definition: "Ban on trade with a country.", translation: "Cấm vận", category: "Economy" },
    { term: "Financial year", partOfSpeech: "n", definition: "12-month period for accounting.", translation: "Năm tài chính", category: "Economy" },
    { term: "Free trade agreement", partOfSpeech: "n", definition: "Treaty eliminating trade barriers.", translation: "Hiệp định thương mại tự do", category: "Economy" },
    { term: "Freelancer", partOfSpeech: "n", definition: "Self-employed person.", translation: "Người làm việc tự do", category: "Economy" },
    { term: "Foreign direct investment", partOfSpeech: "n", definition: "Investment from foreign countries.", translation: "Đầu tư trực tiếp nước ngoài", category: "Economy" },
    { term: "Gig economy", partOfSpeech: "n", definition: "Market of short-term contracts.", translation: "Kinh tế tự do", category: "Economy" },
    { term: "Golden rule", partOfSpeech: "n", definition: "Principle for government spending.", translation: "Nguyên tắc vàng", category: "Economy" },
    { term: "Gross domestic product", partOfSpeech: "n", definition: "Total value of goods produced domestically.", translation: "Tổng sản phẩm nội địa", category: "Economy" },
    { term: "Gross national product", partOfSpeech: "n", definition: "Total national output.", translation: "Tổng sản lượng quốc gia", category: "Economy" },
    { term: "Hyperinflation", partOfSpeech: "n", definition: "Extremely rapid inflation.", translation: "Siêu lạm phát", category: "Economy" },
    { term: "Macroeconomics", partOfSpeech: "n", definition: "Study of economy as a whole.", translation: "Kinh tế vĩ mô", category: "Economy" },
    { term: "Microeconomics", partOfSpeech: "n", definition: "Study of individual economic units.", translation: "Kinh tế vi mô", category: "Economy" },
    { term: "Market economy", partOfSpeech: "n", definition: "Economy driven by supply and demand.", translation: "Kinh tế thị trường", category: "Economy" },
    { term: "Negative equity", partOfSpeech: "n", definition: "When asset value is less than loan.", translation: "Tài sản ròng âm", category: "Economy" },
    { term: "Oligopoly", partOfSpeech: "n", definition: "Market with few competitors.", translation: "Độc quyền nhóm", category: "Economy" },
    { term: "Opportunity cost", partOfSpeech: "n", definition: "Loss of potential gain from alternatives.", translation: "Chi phí cơ hội", category: "Economy" },
    { term: "Recession", partOfSpeech: "n", definition: "Economic decline period.", translation: "Suy thoái", category: "Economy" },
    { term: "Stock market", partOfSpeech: "n", definition: "Market for trading stocks.", translation: "Thị trường chứng khoán", category: "Economy" },
    { term: "Subsidise", partOfSpeech: "v", definition: "To provide financial support.", translation: "Trợ cấp", category: "Economy" },
    { term: "Supply chain", partOfSpeech: "n", definition: "Network of production and distribution.", translation: "Chuỗi cung ứng", category: "Economy" },
    { term: "Tariff", partOfSpeech: "n", definition: "Tax on imported goods.", translation: "Thuế quan", category: "Economy" },
    { term: "Tax haven", partOfSpeech: "n", definition: "Country with low or no taxes.", translation: "Thiên đường thuế", category: "Economy" },
    { term: "Transnational corporation", partOfSpeech: "n", definition: "Company operating in multiple countries.", translation: "Công ty xuyên quốc gia", category: "Economy" },
    { term: "Value-added tax", partOfSpeech: "n", definition: "Tax on goods and services.", translation: "Thuế giá trị gia tăng", category: "Economy" },
    { term: "Supply and demand", partOfSpeech: "n", definition: "Economic forces determining prices.", translation: "Cung và cầu", category: "Economy" },
];
