import { Word } from '../types';

export const LEISURE_VOCABULARY: Word[] = [
    { term: "Amateur", partOfSpeech: "n", definition: "Person who does something for fun, not work.", translation: "Người nghiệp dư", category: "Leisure" },
    { term: "Aficionado", partOfSpeech: "n", definition: "An enthusiast with deep knowledge.", translation: "Người hâm mộ", category: "Leisure" },
    { term: "Archery", partOfSpeech: "n", definition: "Sport of shooting arrows.", translation: "Bắn cung", category: "Leisure" },
    { term: "Arts and crafts", partOfSpeech: "n", definition: "Making decorative items by hand.", translation: "Thủ công mỹ nghệ", category: "Leisure" },
    { term: "Ballroom dancing", partOfSpeech: "n", definition: "Formal partner dancing.", translation: "Khiêu vũ", category: "Leisure" },
    { term: "Binge watching", partOfSpeech: "n", definition: "Watching many episodes at once.", translation: "Cày phim", category: "Leisure" },
    { term: "Board sport", partOfSpeech: "n", definition: "Sport using a board (surfing, skating).", translation: "Thể thao ván trượt", category: "Leisure" },
    { term: "Bodybuilding", partOfSpeech: "n", definition: "Building muscle through exercise.", translation: "Thể hình", category: "Leisure" },
    { term: "Bungee jumping", partOfSpeech: "n", definition: "Jumping from height with elastic cord.", translation: "Nhảy bungee", category: "Leisure" },
    { term: "Calligraphy", partOfSpeech: "n", definition: "Artistic handwriting.", translation: "Thư pháp", category: "Leisure" },
    { term: "Cosplay", partOfSpeech: "n", definition: "Dressing as fictional characters.", translation: "Hóa trang nhân vật", category: "Leisure" },
    { term: "DIY", partOfSpeech: "n", definition: "Do it yourself projects.", translation: "Tự làm", category: "Leisure" },
    { term: "Fencing", partOfSpeech: "n", definition: "Combat sport with swords.", translation: "Đấu kiếm", category: "Leisure" },
    { term: "Flower arranging", partOfSpeech: "n", definition: "Art of arranging flowers.", translation: "Cắm hoa", category: "Leisure" },
    { term: "Gardening", partOfSpeech: "n", definition: "Growing plants.", translation: "Làm vườn", category: "Leisure" },
    { term: "Gymnastics", partOfSpeech: "n", definition: "Physical exercises and acrobatics.", translation: "Thể dục dụng cụ", category: "Leisure" },
    { term: "Handicraft", partOfSpeech: "n", definition: "Items made by hand.", translation: "Đồ thủ công", category: "Leisure" },
    { term: "Horseback riding", partOfSpeech: "n", definition: "Riding horses.", translation: "Cưỡi ngựa", category: "Leisure" },
    { term: "Jogging", partOfSpeech: "n", definition: "Running at a slow pace.", translation: "Chạy bộ", category: "Leisure" },
    { term: "Indoor sports", partOfSpeech: "n", definition: "Sports played inside.", translation: "Thể thao trong nhà", category: "Leisure" },
    { term: "Martial arts", partOfSpeech: "n", definition: "Combat practices for self-defense.", translation: "Võ thuật", category: "Leisure" },
    { term: "Modelling", partOfSpeech: "n", definition: "Making small-scale models.", translation: "Làm mô hình", category: "Leisure" },
    { term: "Motorsports", partOfSpeech: "n", definition: "Racing with motor vehicles.", translation: "Đua xe", category: "Leisure" },
    { term: "Mountaineering", partOfSpeech: "n", definition: "Climbing mountains.", translation: "Leo núi", category: "Leisure" },
    { term: "Paintball", partOfSpeech: "n", definition: "Game shooting paint-filled pellets.", translation: "Súng sơn", category: "Leisure" },
    { term: "Parachuting", partOfSpeech: "n", definition: "Jumping from aircraft with parachute.", translation: "Nhảy dù", category: "Leisure" },
    { term: "Parkour", partOfSpeech: "n", definition: "Moving through obstacles athletically.", translation: "Vượt chướng ngại vật", category: "Leisure" },
    { term: "Pastime", partOfSpeech: "n", definition: "An activity for enjoyment.", translation: "Trò tiêu khiển", category: "Leisure" },
    { term: "Outdoor sports", partOfSpeech: "n", definition: "Sports played outside.", translation: "Thể thao ngoài trời", category: "Leisure" },
    { term: "Photography", partOfSpeech: "n", definition: "Taking photos.", translation: "Nhiếp ảnh", category: "Leisure" },
    { term: "Trampolining", partOfSpeech: "n", definition: "Bouncing on a trampoline.", translation: "Nhảy sàn nhún", category: "Leisure" },
    { term: "Travelling", partOfSpeech: "n", definition: "Going to different places.", translation: "Du lịch", category: "Leisure" },
    { term: "Stress buster", partOfSpeech: "n", definition: "Activity that relieves stress.", translation: "Giải tỏa stress", category: "Leisure" },
    { term: "Therapeutic", partOfSpeech: "adj", definition: "Having healing effects.", translation: "Trị liệu", category: "Leisure" },
];
