import { Word } from '../types';

export const LIFESTYLE_VOCABULARY: Word[] = [
    { term: "Aspect", partOfSpeech: "n", definition: "A particular part or feature.", translation: "Khía cạnh", category: "Lifestyle" },
    { term: "Coastal elite", partOfSpeech: "n", definition: "Wealthy, educated people in coastal cities.", translation: "Giới thượng lưu ven biển", category: "Lifestyle" },
    { term: "Creativity", partOfSpeech: "n", definition: "The ability to create new things.", translation: "Sáng tạo", category: "Lifestyle" },
    { term: "Delight", partOfSpeech: "n", definition: "Great pleasure.", translation: "Điều thích thú", category: "Lifestyle" },
    { term: "Fulfilment", partOfSpeech: "n", definition: "Satisfaction from achieving goals.", translation: "Sự hoàn thành", category: "Lifestyle" },
    { term: "Hassle free", partOfSpeech: "adj", definition: "Without problems.", translation: "Không gặp rắc rối", category: "Lifestyle" },
    { term: "Health-conscious", partOfSpeech: "adj", definition: "Focused on health.", translation: "Quan tâm đến sức khỏe", category: "Lifestyle" },
    { term: "Insight", partOfSpeech: "n", definition: "Deep understanding.", translation: "Sự hiểu biết sâu sắc", category: "Lifestyle" },
    { term: "Materialism", partOfSpeech: "n", definition: "Excessive focus on material possessions.", translation: "Chủ nghĩa vật chất", category: "Lifestyle" },
    { term: "Middle ground", partOfSpeech: "n", definition: "A moderate position.", translation: "Quan điểm trung dung", category: "Lifestyle" },
    { term: "Necessities", partOfSpeech: "n", definition: "Essential things for life.", translation: "Nhu yếu phẩm", category: "Lifestyle" },
    { term: "Non-essentials", partOfSpeech: "n", definition: "Things not absolutely necessary.", translation: "Thứ không cần thiết", category: "Lifestyle" },
    { term: "Outlook", partOfSpeech: "n", definition: "A person's point of view.", translation: "Quan điểm", category: "Lifestyle" },
    { term: "Priority", partOfSpeech: "n", definition: "Something considered more important.", translation: "Ưu tiên", category: "Lifestyle" },
    { term: "Regret", partOfSpeech: "v", definition: "To feel sorry about something.", translation: "Hối tiếc", category: "Lifestyle" },
    { term: "Self-contained", partOfSpeech: "adj", definition: "Independent, not needing others.", translation: "Độc lập", category: "Lifestyle" },
    { term: "Self-expression", partOfSpeech: "n", definition: "Expressing one's personality.", translation: "Thể hiện bản thân", category: "Lifestyle" },
    { term: "Selfless", partOfSpeech: "adj", definition: "Thinking of others first.", translation: "Vị tha", category: "Lifestyle" },
    { term: "Recreational", partOfSpeech: "adj", definition: "Related to leisure activities.", translation: "Giải trí", category: "Lifestyle" },
    { term: "Motivate", partOfSpeech: "v", definition: "To encourage someone.", translation: "Thúc đẩy", category: "Lifestyle" },
    { term: "Viewpoint", partOfSpeech: "n", definition: "A way of thinking.", translation: "Quan điểm", category: "Lifestyle" },
    { term: "Comfortable lifestyle", partOfSpeech: "n", definition: "Living with ease.", translation: "Lối sống thoải mái", category: "Lifestyle" },
    { term: "Extravagant lifestyle", partOfSpeech: "n", definition: "Living luxuriously.", translation: "Lối sống xa hoa", category: "Lifestyle" },
    { term: "Nomadic lifestyle", partOfSpeech: "n", definition: "Moving from place to place.", translation: "Lối sống du mục", category: "Lifestyle" },
    { term: "Sedentary lifestyle", partOfSpeech: "n", definition: "Lifestyle with little exercise.", translation: "Lối sống ít vận động", category: "Lifestyle" },
    { term: "Simple lifestyle", partOfSpeech: "n", definition: "Living with few possessions.", translation: "Lối sống đơn giản", category: "Lifestyle" },
    { term: "Downshifting", partOfSpeech: "n", definition: "Switching to a simpler life.", translation: "Sống chậm lại", category: "Lifestyle" },
    { term: "Work-life balance", partOfSpeech: "n", definition: "Balance between work and personal time.", translation: "Cân bằng công việc-cuộc sống", category: "Lifestyle" },
    { term: "Daily routine", partOfSpeech: "n", definition: "Regular daily activities.", translation: "Thói quen hàng ngày", category: "Lifestyle" },
    { term: "Lifelong ambition", partOfSpeech: "n", definition: "A goal for one's whole life.", translation: "Tham vọng suốt đời", category: "Lifestyle" },
    { term: "Live life to its fullest", partOfSpeech: "phrase", definition: "To enjoy life completely.", translation: "Sống hết mình", category: "Lifestyle" },
    { term: "Standard of living", partOfSpeech: "n", definition: "Level of comfort and wealth.", translation: "Mức sống", category: "Lifestyle" },
];
