import { Word } from '../types';

export const LITERATURE_VOCABULARY: Word[] = [
    { term: "Allegory", partOfSpeech: "n", definition: "A story with a hidden moral or political meaning.", translation: "Truyện ngụ ngôn", category: "Literature" },
    { term: "Appealing", partOfSpeech: "adj", definition: "Attractive and interesting.", translation: "Hấp dẫn, thú vị", category: "Literature" },
    { term: "Appendix", partOfSpeech: "n", definition: "A separate section at the end of a book providing additional information.", translation: "Phụ lục", category: "Literature" },
    { term: "Autobiography", partOfSpeech: "n", definition: "Life story written by that person.", translation: "Hồi ký", category: "Literature" },
    { term: "Backstory", partOfSpeech: "n", definition: "Events that happened before the main story.", translation: "Câu chuyện nền", category: "Literature" },
    { term: "Characterization", partOfSpeech: "n", definition: "The way characters in a book are created by a writer.", translation: "Sự mô tả đặc điểm nhân vật", category: "Literature" },
    { term: "Comic strip", partOfSpeech: "n", definition: "Short humorous stories with funny drawings.", translation: "Truyện tranh liên hoàn", category: "Literature" },
    { term: "Dramatist", partOfSpeech: "n", definition: "A person who writes plays for TV or theater.", translation: "Nhà soạn kịch", category: "Literature" },
    { term: "First-person", partOfSpeech: "adj", definition: "Writing about oneself using 'I' or 'we'.", translation: "Viết ở ngôi thứ nhất", category: "Literature" },
    { term: "Gripping", partOfSpeech: "adj", definition: "Holding attention strongly.", translation: "Thu hút sự chú ý", category: "Literature" },
    { term: "Hardcover book", partOfSpeech: "n", definition: "A book with a stiff cover.", translation: "Sách bìa cứng", category: "Literature" },
    { term: "Heavy", partOfSpeech: "adj", definition: "Very serious or difficult to understand (literary work).", translation: "Nghiêm túc/khó hiểu", category: "Literature" },
    { term: "Inspiration", partOfSpeech: "n", definition: "A feeling of enthusiasm.", translation: "Cảm hứng", category: "Literature" },
    { term: "Intriguing", partOfSpeech: "adj", definition: "Arousing curiosity or interest.", translation: "Hấp dẫn, kích thích sự tò mò", category: "Literature" },
    { term: "Ironic", partOfSpeech: "adj", definition: "Using words to convey opposite meaning.", translation: "Mỉa mai", category: "Literature" },
    { term: "Lampoon", partOfSpeech: "n", definition: "A piece of writing that criticizes someone humorously.", translation: "Bài viết châm biếm", category: "Literature" },
    { term: "Narration", partOfSpeech: "n", definition: "The act of telling a story.", translation: "Tường thuật, kể chuyện", category: "Literature" },
    { term: "Pamphlet", partOfSpeech: "n", definition: "A small booklet with information on a specific topic.", translation: "Sách mỏng", category: "Literature" },
    { term: "Paperback book", partOfSpeech: "n", definition: "A book with a soft cover.", translation: "Sách bìa mềm", category: "Literature" },
    { term: "Prose", partOfSpeech: "n", definition: "Written language in its ordinary form.", translation: "Văn xuôi", category: "Literature" },
    { term: "Sequel", partOfSpeech: "n", definition: "A book continuing a previous story.", translation: "Hậu truyện", category: "Literature" },
    { term: "Symbolism", partOfSpeech: "n", definition: "The use of symbols to represent ideas.", translation: "Biểu tượng", category: "Literature" },
    { term: "Third-person", partOfSpeech: "adj", definition: "Writing about others using 'he' or 'she'.", translation: "Viết ở ngôi thứ ba", category: "Literature" },
    { term: "To co-author", partOfSpeech: "v", definition: "To write something together with another author.", translation: "Đồng tác giả", category: "Literature" },
    { term: "To compose", partOfSpeech: "v", definition: "To create or write something.", translation: "Sáng tác", category: "Literature" },
    { term: "To proofread", partOfSpeech: "v", definition: "To read and correct errors in written text.", translation: "Đọc lại và sửa lỗi", category: "Literature" },
    { term: "To script", partOfSpeech: "v", definition: "To write a script.", translation: "Viết kịch bản", category: "Literature" },
    { term: "Title page", partOfSpeech: "n", definition: "The page with title, author, and publisher.", translation: "Trang tiêu đề", category: "Literature" },
    { term: "Tragic", partOfSpeech: "adj", definition: "Related to tragedy.", translation: "Bi thảm", category: "Literature" },
    { term: "Trilogy", partOfSpeech: "n", definition: "A group of three related works.", translation: "Tác phẩm bộ ba", category: "Literature" },
    { term: "True crime", partOfSpeech: "n", definition: "Fiction about real murders involving real people.", translation: "Tội ác có thật", category: "Literature" },
    { term: "Twist", partOfSpeech: "n", definition: "An unexpected development in a story.", translation: "Bước ngoặt", category: "Literature" },
    { term: "Whodunnit", partOfSpeech: "n", definition: "A detective story with a complex plot.", translation: "Truyện trinh thám", category: "Literature" },
    { term: "Alliteration", partOfSpeech: "n", definition: "Repetition of initial consonant sounds.", translation: "Phép điệp âm", category: "Literature" },
    { term: "Anachronism", partOfSpeech: "n", definition: "Something out of its time period.", translation: "Lỗi thời", category: "Literature" },
    { term: "Byline", partOfSpeech: "n", definition: "Short phrase showing author's name.", translation: "Dòng tên tác giả", category: "Literature" },
    { term: "Canon", partOfSpeech: "n", definition: "Recognized works of an author.", translation: "Kinh điển", category: "Literature" },
    { term: "Caption", partOfSpeech: "n", definition: "Text accompanying an illustration.", translation: "Lời chú thích", category: "Literature" },
    { term: "Catharsis", partOfSpeech: "n", definition: "Release of strong emotions through an activity.", translation: "Giải phóng cảm xúc", category: "Literature" },
    { term: "Copyright", partOfSpeech: "n", definition: "Legal right to publish a work.", translation: "Bản quyền", category: "Literature" },
    { term: "Couplet", partOfSpeech: "n", definition: "Two rhyming lines of equal length in poetry.", translation: "Cặp câu thơ", category: "Literature" },
    { term: "Denouement", partOfSpeech: "n", definition: "The final part of a narrative.", translation: "Kết cục", category: "Literature" },
    { term: "Discourse", partOfSpeech: "n", definition: "Written or spoken communication.", translation: "Diễn đạt, đàm luận", category: "Literature" },
    { term: "Dystopia", partOfSpeech: "n", definition: "An imagined state where everything is bad.", translation: "Phản địa đàng", category: "Literature" },
    { term: "Elegy", partOfSpeech: "n", definition: "A sad poem or song.", translation: "Khúc bi ca", category: "Literature" },
    { term: "Epithet", partOfSpeech: "n", definition: "A descriptive word or phrase.", translation: "Tính ngữ, biệt danh", category: "Literature" },
    { term: "Exegesis", partOfSpeech: "n", definition: "Critical explanation or interpretation.", translation: "Chú giải, bình luận", category: "Literature" },
    { term: "Free-verse", partOfSpeech: "n", definition: "Poetry without traditional rules of rhyme.", translation: "Thơ tự do", category: "Literature" },
    { term: "Frontlist", partOfSpeech: "n", definition: "A publisher's newest book list.", translation: "Danh sách sách mới nhất", category: "Literature" },
    { term: "Hubris", partOfSpeech: "n", definition: "Excessive pride or arrogance.", translation: "Sự ngạo mạn", category: "Literature" },
    { term: "Hyperbole", partOfSpeech: "n", definition: "Exaggerated statements.", translation: "Lời ngoa dụ", category: "Literature" },
    { term: "Jargon", partOfSpeech: "n", definition: "Specialized language of a group.", translation: "Biệt ngữ", category: "Literature" },
    { term: "Monologue", partOfSpeech: "n", definition: "A long speech by one actor.", translation: "Độc thoại", category: "Literature" },
    { term: "Narrative", partOfSpeech: "n", definition: "A story or account of events.", translation: "Tường thuật, kể chuyện", category: "Literature" },
    { term: "Onomatopoeia", partOfSpeech: "n", definition: "Words that imitate sounds.", translation: "Từ tượng thanh", category: "Literature" },
    { term: "Paradigmatic", partOfSpeech: "adj", definition: "Serving as a model or pattern.", translation: "Kiểu mẫu, khuôn mẫu", category: "Literature" },
    { term: "Pathos", partOfSpeech: "n", definition: "Quality that evokes pity or sadness.", translation: "Tính chất cảm động", category: "Literature" },
    { term: "Plot", partOfSpeech: "n", definition: "The main events of a story.", translation: "Cốt truyện", category: "Literature" },
    { term: "Prosody", partOfSpeech: "n", definition: "The study of poetic meter.", translation: "Nghiên cứu về thể thơ", category: "Literature" },
    { term: "Pun", partOfSpeech: "n", definition: "A play on words.", translation: "Chơi chữ", category: "Literature" },
    { term: "Soliloquy", partOfSpeech: "n", definition: "Speaking one's thoughts aloud when alone.", translation: "Độc thoại nội tâm", category: "Literature" },
    { term: "Stanza", partOfSpeech: "n", definition: "A group of lines in a poem.", translation: "Khổ thơ", category: "Literature" },
    { term: "Story arc", partOfSpeech: "n", definition: "The chronological structure of a story.", translation: "Cấu trúc cốt truyện", category: "Literature" },
    { term: "Subplot", partOfSpeech: "n", definition: "A secondary plot supporting the main story.", translation: "Cốt truyện phụ", category: "Literature" },
    { term: "Synopsis", partOfSpeech: "n", definition: "A brief summary.", translation: "Bản tóm tắt", category: "Literature" },
    { term: "To travesty", partOfSpeech: "v", definition: "To parody or imitate someone's style.", translation: "Nhại, bắt chước", category: "Literature" },
    { term: "Trope", partOfSpeech: "n", definition: "A figurative use of a word or phrase.", translation: "Phép ẩn dụ văn học", category: "Literature" },
];
