import { Word } from '../types';

export const MIGRATION_VOCABULARY: Word[] = [
    { term: "Asylum-seeker", partOfSpeech: "n", definition: "Someone seeking refugee protection.", translation: "Người xin tị nạn", category: "Migration" },
    { term: "Asylum", partOfSpeech: "n", definition: "Protection given by a country.", translation: "Tị nạn", category: "Migration" },
    { term: "Chaos", partOfSpeech: "n", definition: "Complete disorder.", translation: "Hỗn loạn", category: "Migration" },
    { term: "Counter-urbanization", partOfSpeech: "n", definition: "Movement from cities to rural areas.", translation: "Chống đô thị hóa", category: "Migration" },
    { term: "Deportation", partOfSpeech: "n", definition: "Forcing someone to leave a country.", translation: "Trục xuất", category: "Migration" },
    { term: "Economic migrant", partOfSpeech: "n", definition: "Person moving for better work.", translation: "Di cư vì kinh tế", category: "Migration" },
    { term: "Emigration", partOfSpeech: "n", definition: "Leaving one's country.", translation: "Sự di cư", category: "Migration" },
    { term: "Flee", partOfSpeech: "v", definition: "To run away from danger.", translation: "Chạy trốn", category: "Migration" },
    { term: "Genocide", partOfSpeech: "n", definition: "Mass killing of a group.", translation: "Diệt chủng", category: "Migration" },
    { term: "Humanitarian", partOfSpeech: "adj", definition: "Concerned with human welfare.", translation: "Nhân đạo", category: "Migration" },
    { term: "Human rights", partOfSpeech: "n", definition: "Basic rights everyone should have.", translation: "Quyền con người", category: "Migration" },
    { term: "Immigrant", partOfSpeech: "n", definition: "Person who moves to a new country.", translation: "Người nhập cư", category: "Migration" },
    { term: "Immigration laws", partOfSpeech: "n", definition: "Laws about entering a country.", translation: "Luật nhập cư", category: "Migration" },
    { term: "International migration", partOfSpeech: "n", definition: "Moving across countries.", translation: "Di cư quốc tế", category: "Migration" },
    { term: "Interregional migration", partOfSpeech: "n", definition: "Moving within a country.", translation: "Di cư giữa các vùng", category: "Migration" },
    { term: "Mayhem", partOfSpeech: "n", definition: "Violent disorder.", translation: "Hỗn loạn bạo lực", category: "Migration" },
    { term: "Medical aid", partOfSpeech: "n", definition: "Health assistance.", translation: "Viện trợ y tế", category: "Migration" },
    { term: "Migrant", partOfSpeech: "n", definition: "Person who moves to another place.", translation: "Người di cư", category: "Migration" },
    { term: "Push factor", partOfSpeech: "n", definition: "Reason to leave a place.", translation: "Yếu tố thúc đẩy", category: "Migration" },
    { term: "Refugee", partOfSpeech: "n", definition: "Person forced to flee home.", translation: "Người tị nạn", category: "Migration" },
    { term: "Refugee status", partOfSpeech: "n", definition: "Legal recognition as refugee.", translation: "Tình trạng tị nạn", category: "Migration" },
    { term: "Repatriation", partOfSpeech: "n", definition: "Returning to home country.", translation: "Hồi hương", category: "Migration" },
    { term: "Resettlement", partOfSpeech: "n", definition: "Moving to permanent new home.", translation: "Tái định cư", category: "Migration" },
    { term: "Undocumented", partOfSpeech: "adj", definition: "Without official papers.", translation: "Không có giấy tờ", category: "Migration" },
    { term: "UNHCR", partOfSpeech: "n", definition: "UN Refugee Agency.", translation: "Cao ủy LHQ về người tị nạn", category: "Migration" },
    { term: "Family reunification", partOfSpeech: "n", definition: "Bringing family members together.", translation: "Đoàn tụ gia đình", category: "Migration" },
    { term: "Forced migration", partOfSpeech: "n", definition: "Being made to leave home.", translation: "Di cư cưỡng bức", category: "Migration" },
    { term: "Language barriers", partOfSpeech: "n", definition: "Difficulties due to different languages.", translation: "Rào cản ngôn ngữ", category: "Migration" },
    { term: "Stateless person", partOfSpeech: "n", definition: "Person without citizenship.", translation: "Người không quốc tịch", category: "Migration" },
    { term: "Voluntary migration", partOfSpeech: "n", definition: "Choosing to move.", translation: "Di cư tự nguyện", category: "Migration" },
];
