import { Word } from '../types';

export const NUTRITION_VOCABULARY: Word[] = [
    { term: "Bolt down", partOfSpeech: "v", definition: "To eat a large amount of food quickly.", translation: "Ăn nhanh", category: "Nutrition" },
    { term: "Candlelit dinner", partOfSpeech: "n", definition: "A romantic dinner by candlelight.", translation: "Bữa tối lãng mạn bên nến", category: "Nutrition" },
    { term: "Daily consumption", partOfSpeech: "n", definition: "Amount eaten daily.", translation: "Mức tiêu thụ hàng ngày", category: "Nutrition" },
    { term: "Doggy bag", partOfSpeech: "n", definition: "Container for taking leftover food home.", translation: "Hộp đựng thức ăn thừa", category: "Nutrition" },
    { term: "Fine dining", partOfSpeech: "n", definition: "Eating at upscale restaurants.", translation: "Ẩm thực cao cấp", category: "Nutrition" },
    { term: "Gourmet", partOfSpeech: "adj", definition: "High quality and expensive food.", translation: "Sành ăn/Cao cấp", category: "Nutrition" },
    { term: "Home cooked", partOfSpeech: "adj", definition: "Made and eaten at home.", translation: "Nấu tại nhà", category: "Nutrition" },
    { term: "Junk food", partOfSpeech: "n", definition: "Food with little nutritional value.", translation: "Thức ăn vặt", category: "Nutrition" },
    { term: "Mouth-watering", partOfSpeech: "adj", definition: "Looking or smelling delicious.", translation: "Hấp dẫn, thơm ngon", category: "Nutrition" },
    { term: "Potluck", partOfSpeech: "n", definition: "A meal where guests bring dishes.", translation: "Tiệc góp thức ăn", category: "Nutrition" },
    { term: "Preservatives", partOfSpeech: "n", definition: "Substances to prevent spoilage.", translation: "Chất bảo quản", category: "Nutrition" },
    { term: "Pub lunch", partOfSpeech: "n", definition: "Lunch served at a bar.", translation: "Bữa trưa ở quán bar", category: "Nutrition" },
    { term: "Rabbit food", partOfSpeech: "n", definition: "Raw vegetables or salad.", translation: "Rau sống, salad", category: "Nutrition" },
    { term: "Ready meal", partOfSpeech: "n", definition: "Pre-cooked meal to reheat.", translation: "Bữa ăn nấu sẵn", category: "Nutrition" },
    { term: "Staple food", partOfSpeech: "n", definition: "Basic food consumed regularly.", translation: "Thực phẩm thiết yếu", category: "Nutrition" },
    { term: "Teetotal", partOfSpeech: "adj", definition: "Choosing not to drink alcohol.", translation: "Không uống rượu", category: "Nutrition" },
    { term: "Vegetarian diet", partOfSpeech: "n", definition: "Diet without meat or fish.", translation: "Chế độ ăn chay", category: "Nutrition" },
    { term: "Balanced diet", partOfSpeech: "n", definition: "Diet with proper nutrition.", translation: "Chế độ ăn cân bằng", category: "Nutrition" },
    { term: "Food allergy", partOfSpeech: "n", definition: "Allergic reaction to certain foods.", translation: "Dị ứng thực phẩm", category: "Nutrition" },
    { term: "Food intolerance", partOfSpeech: "n", definition: "Difficulty digesting certain foods.", translation: "Không dung nạp thực phẩm", category: "Nutrition" },
    { term: "Food poisoning", partOfSpeech: "n", definition: "Illness from contaminated food.", translation: "Ngộ độc thực phẩm", category: "Nutrition" },
    { term: "Organic food", partOfSpeech: "n", definition: "Food grown without chemicals.", translation: "Thực phẩm hữu cơ", category: "Nutrition" },
    { term: "Processed food", partOfSpeech: "n", definition: "Food that has been altered.", translation: "Thực phẩm chế biến", category: "Nutrition" },
    { term: "Seasonal fruits", partOfSpeech: "n", definition: "Fruits available in specific seasons.", translation: "Trái cây theo mùa", category: "Nutrition" },
    { term: "Exotic foods", partOfSpeech: "n", definition: "Foods from other countries.", translation: "Thực phẩm ngoại lai", category: "Nutrition" },
    { term: "Fussy eater", partOfSpeech: "n", definition: "Someone very picky about food.", translation: "Người kén ăn", category: "Nutrition" },
    { term: "Genetically modified food", partOfSpeech: "n", definition: "Food with altered genes.", translation: "Thực phẩm biến đổi gen", category: "Nutrition" },
    { term: "Nutritional benefits", partOfSpeech: "n", definition: "Health benefits from food.", translation: "Lợi ích dinh dưỡng", category: "Nutrition" },
];
