import { Word } from '../types';

export const PERSONALITY_VOCABULARY: Word[] = [
    { term: "Affable", partOfSpeech: "adj", definition: "Friendly and easy to talk to.", translation: "Niềm nở", category: "Personality" },
    { term: "Aloof", partOfSpeech: "adj", definition: "Distant and unfriendly.", translation: "Xa cách", category: "Personality" },
    { term: "Amicable", partOfSpeech: "adj", definition: "Friendly and pleasant.", translation: "Thân thiện", category: "Personality" },
    { term: "Apathetic", partOfSpeech: "adj", definition: "Lacking interest or enthusiasm.", translation: "Thờ ơ", category: "Personality" },
    { term: "Belligerent", partOfSpeech: "adj", definition: "Aggressive and hostile.", translation: "Hiếu chiến", category: "Personality" },
    { term: "Benevolent", partOfSpeech: "adj", definition: "Kind and generous.", translation: "Nhân từ", category: "Personality" },
    { term: "Boisterous", partOfSpeech: "adj", definition: "Noisy and energetic.", translation: "Ồn ào", category: "Personality" },
    { term: "Broad-minded", partOfSpeech: "adj", definition: "Open to different ideas.", translation: "Tư tưởng rộng rãi", category: "Personality" },
    { term: "Cantankerous", partOfSpeech: "adj", definition: "Bad-tempered and argumentative.", translation: "Hay gắt gỏng", category: "Personality" },
    { term: "Capricious", partOfSpeech: "adj", definition: "Unpredictable and changeable.", translation: "Thất thường", category: "Personality" },
    { term: "Chivalrous", partOfSpeech: "adj", definition: "Courteous and honorable.", translation: "Hào hiệp", category: "Personality" },
    { term: "Cynical", partOfSpeech: "adj", definition: "Distrustful of others' motives.", translation: "Hoài nghi", category: "Personality" },
    { term: "Demure", partOfSpeech: "adj", definition: "Modest and reserved.", translation: "Kín đáo", category: "Personality" },
    { term: "Diplomatic", partOfSpeech: "adj", definition: "Tactful in dealing with others.", translation: "Khéo léo", category: "Personality" },
    { term: "Dogmatic", partOfSpeech: "adj", definition: "Stubbornly holding beliefs.", translation: "Giáo điều", category: "Personality" },
    { term: "Eccentric", partOfSpeech: "adj", definition: "Unconventional and strange.", translation: "Lập dị", category: "Personality" },
    { term: "Erudite", partOfSpeech: "adj", definition: "Having great knowledge.", translation: "Uyên bác", category: "Personality" },
    { term: "Extremism", partOfSpeech: "n", definition: "Holding extreme views.", translation: "Chủ nghĩa cực đoan", category: "Personality" },
    { term: "Exuberant", partOfSpeech: "adj", definition: "Full of energy and enthusiasm.", translation: "Hăng hái", category: "Personality" },
    { term: "Fastidious", partOfSpeech: "adj", definition: "Very careful about details.", translation: "Cầu kỳ", category: "Personality" },
    { term: "Flamboyant", partOfSpeech: "adj", definition: "Showy and confident.", translation: "Phô trương", category: "Personality" },
    { term: "Genuine", partOfSpeech: "adj", definition: "Sincere and honest.", translation: "Chân thành", category: "Personality" },
    { term: "Gregarious", partOfSpeech: "adj", definition: "Sociable and outgoing.", translation: "Hòa đồng", category: "Personality" },
    { term: "Hypocrite", partOfSpeech: "n", definition: "Person who pretends to be virtuous.", translation: "Người đạo đức giả", category: "Personality" },
    { term: "Idealist", partOfSpeech: "n", definition: "Person with high ideals.", translation: "Người lý tưởng hóa", category: "Personality" },
    { term: "Imaginative", partOfSpeech: "adj", definition: "Creative and inventive.", translation: "Giàu trí tưởng tượng", category: "Personality" },
    { term: "Impetuous", partOfSpeech: "adj", definition: "Acting without thinking.", translation: "Bốc đồng", category: "Personality" },
    { term: "Indolent", partOfSpeech: "adj", definition: "Lazy.", translation: "Lười biếng", category: "Personality" },
    { term: "Insecure", partOfSpeech: "adj", definition: "Not confident.", translation: "Thiếu tự tin", category: "Personality" },
    { term: "Insensitive", partOfSpeech: "adj", definition: "Not caring about others' feelings.", translation: "Vô cảm", category: "Personality" },
    { term: "Irascible", partOfSpeech: "adj", definition: "Easily angered.", translation: "Nóng nảy", category: "Personality" },
    { term: "Level-headed", partOfSpeech: "adj", definition: "Calm and sensible.", translation: "Bình tĩnh", category: "Personality" },
    { term: "Materialist", partOfSpeech: "n", definition: "Person focused on possessions.", translation: "Người trọng vật chất", category: "Personality" },
    { term: "Mature", partOfSpeech: "adj", definition: "Fully developed, sensible.", translation: "Trưởng thành", category: "Personality" },
    { term: "Meddlesome", partOfSpeech: "adj", definition: "Interfering in others' affairs.", translation: "Hay xen vào", category: "Personality" },
    { term: "Modest", partOfSpeech: "adj", definition: "Humble, not boastful.", translation: "Khiêm tốn", category: "Personality" },
    { term: "Naive", partOfSpeech: "adj", definition: "Lacking experience or wisdom.", translation: "Ngây thơ", category: "Personality" },
    { term: "Obstinate", partOfSpeech: "adj", definition: "Stubbornly refusing to change.", translation: "Cứng đầu", category: "Personality" },
    { term: "Open-minded", partOfSpeech: "adj", definition: "Willing to consider new ideas.", translation: "Cởi mở", category: "Personality" },
    { term: "Optimist", partOfSpeech: "n", definition: "Person who expects the best.", translation: "Người lạc quan", category: "Personality" },
    { term: "Pessimist", partOfSpeech: "n", definition: "Person who expects the worst.", translation: "Người bi quan", category: "Personality" },
    { term: "Realist", partOfSpeech: "n", definition: "Person who sees things as they are.", translation: "Người thực tế", category: "Personality" },
    { term: "Rebellious", partOfSpeech: "adj", definition: "Resisting authority.", translation: "Hay chống đối", category: "Personality" },
    { term: "Risk taker", partOfSpeech: "n", definition: "Person who takes chances.", translation: "Người mạo hiểm", category: "Personality" },
    { term: "Taciturn", partOfSpeech: "adj", definition: "Saying very little.", translation: "Ít nói", category: "Personality" },
    { term: "Volatile", partOfSpeech: "adj", definition: "Changing moods quickly.", translation: "Hay thay đổi", category: "Personality" },
    { term: "People person", partOfSpeech: "n", definition: "Outgoing, sociable person.", translation: "Người hướng ngoại", category: "Personality" },
    { term: "Big-mouth", partOfSpeech: "n", definition: "Person who can't keep secrets.", translation: "Người không giữ bí mật", category: "Personality" },
    { term: "Busybody", partOfSpeech: "n", definition: "Nosy person.", translation: "Người tọc mạch", category: "Personality" },
    { term: "Chatterbox", partOfSpeech: "n", definition: "Person who talks too much.", translation: "Người nói nhiều", category: "Personality" },
    { term: "Cold fish", partOfSpeech: "n", definition: "Unemotional person.", translation: "Người vô cảm", category: "Personality" },
    { term: "Dark horse", partOfSpeech: "n", definition: "Person with hidden abilities.", translation: "Người ẩn tài", category: "Personality" },
    { term: "Down-to-earth", partOfSpeech: "adj", definition: "Practical and realistic.", translation: "Thực tế", category: "Personality" },
    { term: "Eager beaver", partOfSpeech: "n", definition: "Very enthusiastic person.", translation: "Người hăng hái", category: "Personality" },
    { term: "Lone wolf", partOfSpeech: "n", definition: "Person who prefers being alone.", translation: "Sói cô độc", category: "Personality" },
    { term: "Smart cookie", partOfSpeech: "n", definition: "Clever person.", translation: "Người thông minh", category: "Personality" },
    { term: "Wet blanket", partOfSpeech: "n", definition: "Person who ruins others' fun.", translation: "Người làm mất vui", category: "Personality" },
];
