import { Word } from '../types';

export const SPACE_VOCABULARY: Word[] = [
    { term: "Constellation", partOfSpeech: "n", definition: "A group of stars forming a pattern.", translation: "Chòm sao", category: "Space" },
    { term: "Lunar module", partOfSpeech: "n", definition: "Spacecraft for traveling to the moon.", translation: "Mô-đun mặt trăng", category: "Space" },
    { term: "Space rocket", partOfSpeech: "n", definition: "Rocket for space travel.", translation: "Tên lửa vũ trụ", category: "Space" },
    { term: "Satellite", partOfSpeech: "n", definition: "Object orbiting a planet.", translation: "Vệ tinh", category: "Space" },
    { term: "Solar eclipse", partOfSpeech: "n", definition: "Moon blocking the sun.", translation: "Nhật thực", category: "Space" },
    { term: "Lunar eclipse", partOfSpeech: "n", definition: "Earth's shadow on the moon.", translation: "Nguyệt thực", category: "Space" },
    { term: "Space probe", partOfSpeech: "n", definition: "Unmanned spacecraft for exploration.", translation: "Tàu thăm dò vũ trụ", category: "Space" },
    { term: "Space shuttle", partOfSpeech: "n", definition: "Reusable spacecraft.", translation: "Tàu con thoi", category: "Space" },
    { term: "Acceleration", partOfSpeech: "n", definition: "Rate of speed increase.", translation: "Gia tốc", category: "Space" },
    { term: "Aerodynamics", partOfSpeech: "n", definition: "Study of air movement.", translation: "Khí động lực học", category: "Space" },
    { term: "Aerospace", partOfSpeech: "n", definition: "Industry of aircraft and spacecraft.", translation: "Hàng không vũ trụ", category: "Space" },
    { term: "Asteroid", partOfSpeech: "n", definition: "Rocky object orbiting the sun.", translation: "Tiểu hành tinh", category: "Space" },
    { term: "Astrobiology", partOfSpeech: "n", definition: "Study of life in space.", translation: "Sinh học vũ trụ", category: "Space" },
    { term: "Astronaut", partOfSpeech: "n", definition: "Person trained for space travel.", translation: "Phi hành gia", category: "Space" },
    { term: "Astronomy", partOfSpeech: "n", definition: "Study of celestial objects.", translation: "Thiên văn học", category: "Space" },
    { term: "Black hole", partOfSpeech: "n", definition: "Region with extreme gravity.", translation: "Hố đen", category: "Space" },
    { term: "Background radiation", partOfSpeech: "n", definition: "Cosmic microwave radiation.", translation: "Bức xạ nền", category: "Space" },
    { term: "Celestial body", partOfSpeech: "n", definition: "Natural object in space.", translation: "Thiên thể", category: "Space" },
    { term: "Comet", partOfSpeech: "n", definition: "Icy object with a tail.", translation: "Sao chổi", category: "Space" },
    { term: "Cosmic ray", partOfSpeech: "n", definition: "High-energy particles from space.", translation: "Tia vũ trụ", category: "Space" },
    { term: "Cosmos", partOfSpeech: "n", definition: "The universe as a whole.", translation: "Vũ trụ", category: "Space" },
    { term: "Cosmology", partOfSpeech: "n", definition: "Study of the universe.", translation: "Vũ trụ học", category: "Space" },
    { term: "Doppler effect", partOfSpeech: "n", definition: "Change in wave frequency with movement.", translation: "Hiệu ứng Doppler", category: "Space" },
    { term: "Dwarf planet", partOfSpeech: "n", definition: "Small planet-like object.", translation: "Hành tinh lùn", category: "Space" },
    { term: "Exoplanet", partOfSpeech: "n", definition: "Planet outside our solar system.", translation: "Ngoại hành tinh", category: "Space" },
    { term: "Full moon", partOfSpeech: "n", definition: "Moon fully illuminated.", translation: "Trăng tròn", category: "Space" },
    { term: "Galactic cluster", partOfSpeech: "n", definition: "Group of galaxies.", translation: "Cụm thiên hà", category: "Space" },
    { term: "Globular cluster", partOfSpeech: "n", definition: "Spherical star cluster.", translation: "Cụm sao hình cầu", category: "Space" },
    { term: "Hydrosphere", partOfSpeech: "n", definition: "All water on a planet.", translation: "Thủy quyển", category: "Space" },
    { term: "Intergalactic", partOfSpeech: "adj", definition: "Between galaxies.", translation: "Giữa các thiên hà", category: "Space" },
    { term: "Interplanetary", partOfSpeech: "adj", definition: "Between planets.", translation: "Giữa các hành tinh", category: "Space" },
    { term: "Meteor", partOfSpeech: "n", definition: "Shooting star.", translation: "Sao băng", category: "Space" },
    { term: "NASA", partOfSpeech: "n", definition: "US space agency.", translation: "Cơ quan vũ trụ Mỹ", category: "Space" },
    { term: "Nebula", partOfSpeech: "n", definition: "Cloud of gas and dust in space.", translation: "Tinh vân", category: "Space" },
    { term: "New moon", partOfSpeech: "n", definition: "Moon not visible.", translation: "Trăng non", category: "Space" },
    { term: "Spacecraft", partOfSpeech: "n", definition: "Vehicle for space travel.", translation: "Tàu vũ trụ", category: "Space" },
    { term: "Spectroscope", partOfSpeech: "n", definition: "Instrument to analyze light.", translation: "Quang phổ kế", category: "Space" },
    { term: "Speed of light", partOfSpeech: "n", definition: "Fastest possible speed.", translation: "Tốc độ ánh sáng", category: "Space" },
    { term: "Telescope", partOfSpeech: "n", definition: "Instrument to view distant objects.", translation: "Kính viễn vọng", category: "Space" },
    { term: "Big Bang theory", partOfSpeech: "n", definition: "Theory of universe's origin.", translation: "Thuyết vụ nổ lớn", category: "Space" },
    { term: "Milky Way", partOfSpeech: "n", definition: "Our galaxy.", translation: "Dải Ngân hà", category: "Space" },
    { term: "UFO", partOfSpeech: "n", definition: "Unidentified flying object.", translation: "Vật thể bay không xác định", category: "Space" },
    { term: "Supernova", partOfSpeech: "n", definition: "Exploding star.", translation: "Siêu tân tinh", category: "Space" },
    { term: "Zero gravity", partOfSpeech: "n", definition: "Weightlessness.", translation: "Không trọng lực", category: "Space" },
    { term: "Space tourism", partOfSpeech: "n", definition: "Recreational space travel.", translation: "Du lịch vũ trụ", category: "Space" },
    { term: "Terraforming", partOfSpeech: "n", definition: "Making a planet Earth-like.", translation: "Địa khai hóa", category: "Space" },
    { term: "Extraterrestrial life", partOfSpeech: "n", definition: "Life beyond Earth.", translation: "Sự sống ngoài Trái Đất", category: "Space" },
];
