import { Word } from '../types';

export const TECHNOLOGY_VOCABULARY: Word[] = [
    { term: "Techie", partOfSpeech: "n", definition: "Person who knows a lot about technology.", translation: "Dân kỹ thuật", category: "Technology" },
    { term: "Adverse effect", partOfSpeech: "n", definition: "A harmful or negative effect.", translation: "Tác dụng bất lợi", category: "Technology" },
    { term: "AI", partOfSpeech: "n", definition: "Artificial intelligence.", translation: "Trí tuệ nhân tạo", category: "Technology" },
    { term: "Automatons", partOfSpeech: "n", definition: "Automatic devices.", translation: "Thiết bị tự động", category: "Technology" },
    { term: "Catfishing", partOfSpeech: "n", definition: "Creating fake online identity to deceive.", translation: "Lừa đảo danh tính", category: "Technology" },
    { term: "ChatGPT", partOfSpeech: "n", definition: "AI chatbot for conversations.", translation: "Chatbot AI", category: "Technology" },
    { term: "Cutting-edge", partOfSpeech: "adj", definition: "Highly advanced and modern.", translation: "Tiên tiến nhất", category: "Technology" },
    { term: "Cybersecurity", partOfSpeech: "n", definition: "Protection against digital attacks.", translation: "An ninh mạng", category: "Technology" },
    { term: "Debut", partOfSpeech: "n", definition: "First public appearance.", translation: "Sự xuất hiện lần đầu", category: "Technology" },
    { term: "Electronic funds transfer", partOfSpeech: "n", definition: "Online payment.", translation: "Chuyển tiền điện tử", category: "Technology" },
    { term: "Game changer", partOfSpeech: "n", definition: "Something that significantly changes a situation.", translation: "Thay đổi cuộc chơi", category: "Technology" },
    { term: "Harass", partOfSpeech: "v", definition: "To bother or intimidate.", translation: "Quấy rối", category: "Technology" },
    { term: "Humanoid", partOfSpeech: "n", definition: "Robot resembling a human.", translation: "Robot hình người", category: "Technology" },
    { term: "Internet addict", partOfSpeech: "n", definition: "Person addicted to the internet.", translation: "Người nghiện internet", category: "Technology" },
    { term: "Internet of things", partOfSpeech: "n", definition: "Network of connected devices.", translation: "Internet vạn vật", category: "Technology" },
    { term: "Silver surfer", partOfSpeech: "n", definition: "Older person who uses the internet.", translation: "Người lớn tuổi dùng internet", category: "Technology" },
    { term: "Technophile", partOfSpeech: "n", definition: "Person who loves technology.", translation: "Người đam mê công nghệ", category: "Technology" },
    { term: "Tech-savvy", partOfSpeech: "adj", definition: "Proficient in using technology.", translation: "Am hiểu công nghệ", category: "Technology" },
    { term: "Technophobe", partOfSpeech: "n", definition: "Person who fears technology.", translation: "Người sợ công nghệ", category: "Technology" },
    { term: "User-friendly", partOfSpeech: "adj", definition: "Easy to use.", translation: "Thân thiện với người dùng", category: "Technology" },
    { term: "Technical breakthrough", partOfSpeech: "n", definition: "Important technological advance.", translation: "Đột phá công nghệ", category: "Technology" },
    { term: "Throw-away society", partOfSpeech: "n", definition: "Society that overuses disposable items.", translation: "Xã hội đồ dùng một lần", category: "Technology" },
    { term: "Advances in technology", partOfSpeech: "n", definition: "Progress in technology.", translation: "Tiến bộ công nghệ", category: "Technology" },
    { term: "Driverless vehicles", partOfSpeech: "n", definition: "Self-driving cars.", translation: "Xe không người lái", category: "Technology" },
    { term: "Emerging technology", partOfSpeech: "n", definition: "New developing technology.", translation: "Công nghệ mới nổi", category: "Technology" },
    { term: "Hacking", partOfSpeech: "n", definition: "Illegally accessing computer systems.", translation: "Xâm nhập hệ thống", category: "Technology" },
    { term: "Online scams", partOfSpeech: "n", definition: "Internet fraud.", translation: "Lừa đảo trực tuyến", category: "Technology" },
    { term: "State-of-the-art", partOfSpeech: "adj", definition: "The most modern available.", translation: "Công nghệ đỉnh cao", category: "Technology" },
    { term: "Robotics technology", partOfSpeech: "n", definition: "Technology related to robots.", translation: "Công nghệ robot", category: "Technology" },
    { term: "Video conferencing", partOfSpeech: "n", definition: "Online video meetings.", translation: "Hội nghị video", category: "Technology" },
    { term: "Virtual relationships", partOfSpeech: "n", definition: "Online relationships.", translation: "Quan hệ ảo", category: "Technology" },
    { term: "Wireless hotspots", partOfSpeech: "n", definition: "Places with WiFi access.", translation: "Điểm truy cập không dây", category: "Technology" },
    { term: "Digital age", partOfSpeech: "n", definition: "Era of digital technology.", translation: "Thời đại kỹ thuật số", category: "Technology" },
    { term: "Go viral", partOfSpeech: "v", definition: "To spread rapidly online.", translation: "Lan truyền rộng rãi", category: "Technology" },
];
