import { Word } from '../types';

export const URBAN_LIFE_VOCABULARY: Word[] = [
    { term: "Apartment buildings", partOfSpeech: "n", definition: "Buildings containing multiple apartments.", translation: "Tòa nhà chung cư", category: "Urban Life" },
    { term: "Art gallery", partOfSpeech: "n", definition: "A place to display art.", translation: "Phòng trưng bày nghệ thuật", category: "Urban Life" },
    { term: "Amenities", partOfSpeech: "n", definition: "Features providing comfort and convenience.", translation: "Tiện nghi", category: "Urban Life" },
    { term: "Amusement park", partOfSpeech: "n", definition: "A park with rides and entertainment.", translation: "Công viên giải trí", category: "Urban Life" },
    { term: "Backstreet", partOfSpeech: "n", definition: "A narrow street, usually in older or poorer areas.", translation: "Phố hẻm", category: "Urban Life" },
    { term: "Botanical garden", partOfSpeech: "n", definition: "A garden for scientific plant study.", translation: "Vườn bách thảo", category: "Urban Life" },
    { term: "Bus route", partOfSpeech: "n", definition: "The path a bus follows.", translation: "Tuyến đường xe buýt", category: "Urban Life" },
    { term: "Bus terminal", partOfSpeech: "n", definition: "A station where buses start/end routes.", translation: "Trạm xe buýt", category: "Urban Life" },
    { term: "City dweller", partOfSpeech: "n", definition: "A person who lives in a city.", translation: "Cư dân thành phố", category: "Urban Life" },
    { term: "Commuter", partOfSpeech: "n", definition: "Person who travels regularly between work and home.", translation: "Người đi làm xa", category: "Urban Life" },
    { term: "Commuter belt", partOfSpeech: "n", definition: "Area around a city where workers live.", translation: "Vành đai cư dân", category: "Urban Life" },
    { term: "Concrete jungle", partOfSpeech: "n", definition: "Dense urban area with many buildings.", translation: "Rừng bê tông", category: "Urban Life" },
    { term: "Congestion", partOfSpeech: "n", definition: "The state of being crowded or blocked.", translation: "Tắc nghẽn", category: "Urban Life" },
    { term: "Conurbation", partOfSpeech: "n", definition: "Extended urban area of several towns.", translation: "Khu mở rộng đô thị", category: "Urban Life" },
    { term: "Convenience store", partOfSpeech: "n", definition: "A small shop open long hours.", translation: "Cửa hàng tiện ích", category: "Urban Life" },
    { term: "Cosmopolitan", partOfSpeech: "adj", definition: "Including people from many countries.", translation: "Mang tính quốc tế", category: "Urban Life" },
    { term: "Cultural centre", partOfSpeech: "n", definition: "A place for cultural activities.", translation: "Trung tâm văn hóa", category: "Urban Life" },
    { term: "Cycle path", partOfSpeech: "n", definition: "A path for bicycles.", translation: "Đường dành cho xe đạp", category: "Urban Life" },
    { term: "Downtown", partOfSpeech: "n", definition: "The central area of a city.", translation: "Khu trung tâm", category: "Urban Life" },
    { term: "Drive-through", partOfSpeech: "n", definition: "Service without leaving your car.", translation: "Cửa hàng phục vụ tại xe", category: "Urban Life" },
    { term: "Exurb", partOfSpeech: "n", definition: "Outer suburban area with wealthy residents.", translation: "Ngoại thành", category: "Urban Life" },
    { term: "Flea market", partOfSpeech: "n", definition: "An outdoor market selling secondhand goods.", translation: "Chợ trời", category: "Urban Life" },
    { term: "Health facilities", partOfSpeech: "n", definition: "Medical buildings like hospitals and clinics.", translation: "Cơ sở y tế", category: "Urban Life" },
    { term: "High street", partOfSpeech: "n", definition: "Main street with shops and businesses.", translation: "Đại lộ thương mại", category: "Urban Life" },
    { term: "Housing estate", partOfSpeech: "n", definition: "A planned residential area.", translation: "Khu dân cư", category: "Urban Life" },
    { term: "Industrial zone", partOfSpeech: "n", definition: "Area for factories and businesses.", translation: "Khu công nghiệp", category: "Urban Life" },
    { term: "Inner city", partOfSpeech: "n", definition: "The central part of a city.", translation: "Nội thành", category: "Urban Life" },
    { term: "Metropolis", partOfSpeech: "n", definition: "A very large, busy city.", translation: "Đô thị", category: "Urban Life" },
    { term: "Multi-storey car park", partOfSpeech: "n", definition: "A building for parking cars on multiple floors.", translation: "Bãi đỗ xe nhiều tầng", category: "Urban Life" },
    { term: "Neighbourhood", partOfSpeech: "n", definition: "A district or community.", translation: "Khu phố", category: "Urban Life" },
    { term: "No-go zone", partOfSpeech: "n", definition: "A dangerous area to avoid.", translation: "Khu vực cấm vào", category: "Urban Life" },
    { term: "Office building", partOfSpeech: "n", definition: "A building containing offices.", translation: "Tòa nhà văn phòng", category: "Urban Life" },
    { term: "Outskirts", partOfSpeech: "n", definition: "Outer parts of a city.", translation: "Vùng ngoại thành", category: "Urban Life" },
    { term: "Pavement café", partOfSpeech: "n", definition: "A café with outdoor seating.", translation: "Cà phê vỉa hè", category: "Urban Life" },
    { term: "Pedestrian zone", partOfSpeech: "n", definition: "Area only for walking.", translation: "Khu vực dành cho người đi bộ", category: "Urban Life" },
    { term: "Residential area", partOfSpeech: "n", definition: "Area where people live.", translation: "Khu dân cư", category: "Urban Life" },
    { term: "Rush hour", partOfSpeech: "n", definition: "Peak traffic time.", translation: "Giờ cao điểm", category: "Urban Life" },
    { term: "Shantytown", partOfSpeech: "n", definition: "Area of poor, cheaply built houses.", translation: "Khu ổ chuột", category: "Urban Life" },
    { term: "Shopping precinct", partOfSpeech: "n", definition: "An area with many shops.", translation: "Khu mua sắm", category: "Urban Life" },
    { term: "Sidewalk", partOfSpeech: "n", definition: "Path for pedestrians beside a road.", translation: "Vỉa hè", category: "Urban Life" },
    { term: "Skyscraper", partOfSpeech: "n", definition: "A very tall modern building.", translation: "Nhà chọc trời", category: "Urban Life" },
    { term: "Sleepy", partOfSpeech: "adj", definition: "Quiet and boring (of a place).", translation: "Buồn tẻ", category: "Urban Life" },
    { term: "Sports facilities", partOfSpeech: "n", definition: "Places for sports like gyms and pools.", translation: "Cơ sở thể thao", category: "Urban Life" },
    { term: "Suburb", partOfSpeech: "n", definition: "Residential area outside city center.", translation: "Vùng ngoại ô", category: "Urban Life" },
    { term: "Megacity", partOfSpeech: "n", definition: "A city with population over 10 million.", translation: "Siêu đô thị", category: "Urban Life" },
    { term: "Road rage", partOfSpeech: "n", definition: "Angry aggressive behavior by drivers.", translation: "Hành vi hung hăng khi lái xe", category: "Urban Life" },
    { term: "Run-down area", partOfSpeech: "n", definition: "An area in poor condition.", translation: "Khu vực xuống cấp", category: "Urban Life" },
    { term: "Sense of community", partOfSpeech: "n", definition: "Feeling of belonging to a group.", translation: "Ý thức cộng đồng", category: "Urban Life" },
];
